name: Python Package using Conda

on: 
  pull_request:
    branches: [dev, master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Test matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    # cache conda packages: https://github.com/conda-incubator/setup-miniconda#caching
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        sudo apt-get update
        # install openslide
        sudo apt-get install openslide-tools
        # install pandoc for making documentation
        sudo apt-get install pandoc
    - name: Setup Miniconda
      # You may pin to the exact commit or the version.
      # uses: conda-incubator/setup-miniconda@f4c00b0ec69bdc87b1ab4972613558dd9f4f36f3
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        environment-file: environment-dev.yml
        activate-environment: pathml
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -m pytest
    - name: Compile docs
      shell: bash -l {0}
      run: |
        cd docs
        make html
